### ISSUE TITLE
Network and PC requirements

### ISSUE THREAD

**Issue by carlosjoserg** [CentroEPiaggio/pacman-DR53#2]
For the last sprint week and to run the demo,  2 PCs with dual network cards are required.

So, these 2 PCs can be online and connected to the robot network simultaneously. This is crucial for last-minutes adjustments and everyone being in sync with the main repository.

The devices are: 
1. `pacman0`: this is the one I regularly use, so all required software is already there up-to-date
2. `pacman1`: There is another PC in the lab, with a keyboard on top labeled as WALKMAN that used to be assigned to Corrado Pavan. I asked around, and nobody is using it, and it has exactly the same specs as `pacman0`.  It needs to be cleaned and fresh install of Ubuntu 14.04 LTS / ROS Indigo / Gazebo 4  (@Tabjones this PC is not to be used by anyone until the demo, therefore, please, leave the classical GNOME desktop as default, it makes setting network profiles easier). 

Information regarding the network configuration and passwords is found [here](https://docs.google.com/drawings/d/1kyQeu9JCw8l99c03lb9CYwT3qcxgAatOyYYRmBtoACc/edit?usp=sharing).

The 3rd PC is the one associated with the head.

**Comment by MirkoFerrati** [comment]
@alessandrosettimi @corradopav guys can you confirm that the WALKMAN computer in Pisa is free to be used by pacman? I recall Alessandro saying that Corrado will be using that pc for walkman simulation from now on when he's in Pisa.

**Comment by alessandrosettimi** [comment]
@carlosjoserg that pc is for walkman, is the most performing one we have in pisa to simulate the walk-man in gazebo. @corradopav uses it also for developing. The reason why nobody used it for a while is because we were at IIT.

**Comment by carlosjoserg** [comment]
Ok, thanks for the clarification and my apologies.

@Tabjones we need to find something similar, for instance, the PC at the phase space is a good candidate, if I remember well it has two network cards as well, but it is also advisable to have that good PC there as well.  There is also an old PC next to where you sit that used to belong to Saber I believe, can you check on that?

@MarcoGabiccini can we buy a new one in case we don't find anything within the pacman resources?

**Comment by Tabjones** [comment]
Ok, also pacman0 has only one network card, i think we could buy a new PCI network card and install it.

**Comment by carlosjoserg** [comment]
@Tabjones `pacman0` is my PC, and it does have 2 network cards, so nevermind that one.

I understand you are talking about the one in the phase space only having one card. In that case, definitely, I would go for a new PC as suggested above (if possible) instead of buying a PCI network card.

**Comment by hamalMarino** [comment]
@MirkoFerrati what about Emmanuel's PC?

**Comment by Tabjones** [comment]
@carlosjoserg wait a sec if pacman0 is your pc, then what is mine ? the one next to Manuel, i thought that one was pacman0 and that one has only one network card. The phase space pc has 2 network cards.

**Comment by MirkoFerrati** [comment]
@hamalMarino  Emmanuel's PC is free to use, but it has only one network adapter!

**Comment by carlosjoserg** [comment]
Ok then. @Tabjones let's buy a new one for `pacman1`.

Be sure to match the specs of my PC (`pacman0`) (or phase space PC, I think is the same) or higher, you decide. Admin  dept. should have the specs. since several PCs has been bought like these.

After the demo, the new one could replace the "kuka PC", for instance, so Manuel can have the current one dedicated for him, you can have the "pacman PC" dedicated to you, the phase space keeps its PC, and peace for all.

**Comment by Tabjones** [comment]
I looked around a bit, probably the best solution would be to let Dell assemble a PC for us. This way we can select exactly what we want inside the PC and they assemble it for us. They also check if the various hardware selected are compatible with each other.

The other alternative would be to buy each hardware separately and then assemble the pc at CentroPiaggio, although this would be surely cheaper it will take me at least an afternoon to assemble it and a lot of effort to chose the right hardware (check motherboard chipset, processor, certified RAM, disks, etc..)

So i would go for the first alternative. I'll coordinate with @MarcoGabiccini for the various burocratics.

**Comment by carlosjoserg** [comment]
I thought the order was already placed at this point, ain't repeating the order from previous acquired PCs easier?

**Comment by Tabjones** [comment]
@carlosjoserg  Yes it would, but i thought we wanted a better one, my bad. If you want to replicate the phase space pc or yours tell me.

**Comment by carlosjoserg** [comment]
Just thought it was easier to repeat the order, but my bad, this is entirely up to you. If you see it clearer, go for it (in that case, I would suggest the first alternative as well, let Dell assemble it for you).

**Comment by Tabjones** [comment]
Pc has arrived and it is already configured. I think i can close this issue
