### ISSUE TITLE
Screen for the reviewers and public

### ISSUE THREAD

**Issue by carlosjoserg** [CentroEPiaggio/pacman-DR53#3]
The main screen in the "Aquarius" should show interesting stuff for reviewers and public. My suggestions are:
1. State manager viewer
2. High-level planner viewer (improved if possible @MirkoFerrati ?)
3. A minimal RVIZ configuration with the necessary stuff to show from the real scene, perhaps only the robot model
4. Any other thing that might be interesting to show from the algorithm internals: database query?

**Comment by hamalMarino** [comment]
Definitely the recognized object(s) in the scene, and possibly an octomap for everything else which should be considered as obstacles

**Comment by carlosjoserg** [comment]
There is no need for this, we have all information we need as displayable in RVIZ
